# Visualisation

mesh_files:
  base:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10/visual/base.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/base.stl

  shoulder:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10/visual/shoulder.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/shoulder.stl

  upper_arm:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10/visual/upperarm.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/upperarm.stl
      mesh_files:

  forearm:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10/visual/forearm.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/forearm.stl

  wrist_1:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10/visual/wrist1.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/wrist1.stl
    visual_offset: -0.1149

  wrist_2:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10/visual/wrist2.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/wrist2.stl
    visual_offset: -0.1158

  wrist_3:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10/visual/wrist3.dae
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/wrist3.stl
    visual_offset: -0.0922

  trolley:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/trolley1.STL
      material:
        name: "LightGrey_trolley"
        color: "0.89 0.91 0.93 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/trolley1.STL

  plate:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/UR_plate.STL
      material:
        name: "LightGrey_plate"
        color: "0.69 0.71 0.83 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10/collision/UR_plate.STL

  ur10_feeder:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/UR10_feeder.STL
      material:
        name: "LightGrey_ur10_feeder"
        color: "0.59 0.61 0.73 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/UR10_feeder.STL
    
  heating_plate1:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate1.STL
      material:
        name: "LightGrey_heating_plate1"
        color: "0.85 0.86 0.92 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate1.STL

  heating_plate2:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate2.STL
      material:
        name: "LightGrey_heating_plate2"
        color: "0.85 0.86 0.92 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate2.STL

  heating_plate_cover1:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate_cover1.STL
      material:
        name: "LightGrey_heating_plate_cover1"
        color: "0.2 0.2 0.2 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate_cover1.STL

  heating_plate_cover2:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate_cover2.STL
      material:
        name: "LightGrey_heating_plate_cover2"
        color: "0.2 0.2 0.2 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate_cover2.STL

  heating_plate_cover3_1:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate_cover3-1.STL
      material:
        name: "Black"
        color: "0.0 0.0 0.0 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate_cover3-1.STL

  heating_plate_cover3_2:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate_cover3-2.STL
      material:
        name: "Black"
        color: "0.0 0.0 0.0 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10_feeder/heating_plate_cover3-2.STL