/**:
  ros__parameters:
    robot_description_kinematics:
      ur_manipulator:
        kinematics_solver: pick_ik/PickIkPlugin
        mode: local                  # or 'global' if seeds are far
        kinematics_solver_timeout: 0.02
        minimal_displacement_weight: 0.001   # ← penalize Δq
        avoid_joint_limits_weight: 0.0
        center_joints_weight: 0.0
      denso_arm:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.001
        kinematics_solver_timeout: 0.3
        kinematics_solver_attempts: 25
