shoulder_pan_joint: 0.0
shoulder_lift_joint: -1.57
elbow_joint: 0.0
wrist_1_joint: -1.57
wrist_2_joint: 0.0
wrist_3_joint: 0.0
denso_joint_1: 0.0
denso_joint_2: 0.0
denso_joint_3: 0.0
denso_joint_4: 0.0 