# Visualisation

mesh_files:
  arf_trolley:
    visual:
      mesh:
        package: ur_description
        path: meshes/arf/Assy_Docking_Cartbase_ARF.STL
      material:
        name: "LightGrey_arf_trolley"
        color: "0.89 0.91 0.93 1.0"
    collision:
      box:
        size: "0.8 0.8 0.86"
        origin: "0 0 -0.43"

  arf_x_axis:
    visual:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_X-Axis.STL
      material:
        name: "Grey_arf_base_plate"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_X-Axis.STL

  arf_y_axis:
    visual:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_Y-Axis.STL
      material:
        name: "Grey_arf_slider_base"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_Y-Axis.STL
  
  arf_jig:
    visual:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_Jig.STL
      material:
        name: "Green_arf_slider_jig"
        color: "0.0 0.5 0.0 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_Jig.STL
  
  arf_front_aircyl:
    visual:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_Air_Cyl_02.STL
      material:
        name: "Green_arf_front_aircyl"
        color: "0.0 0.5 0.0 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_Air_Cyl_02.STL

  arf_back_aircyl:
    visual:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_Air_Cyl_01.STL
      material:
        name: "Green_arf_back_aircyl"
        color: "0.0 0.5 0.0 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/arf/ARF_Air_Cyl_01.STL
