# Visualisation

mesh_files:
  denso_trolley:
    visual:
      mesh:
        package: ur_description
        path: meshes/denso/Assy_Fixing_Cartbase.STL
      material:
        name: "LightGrey_denso_trolley"
        color: "0.89 0.91 0.93 1.0"
    collision:
      box:
        size: "0.8 0.8 0.86"
        origin: "0 0 -0.43"

  denso_slider_jig:
    visual:
      mesh:
        package: ur_description
        path: meshes/denso/denso_slider_jig.STL
      material:
        name: "Grey_denso_slider_jig"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/denso/denso_slider_jig.STL
      