# Visualisation

mesh_files:
  feeder_base:
    visual:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_Base_Assy.STL
      material:
        name: "LightGrey_feeder_base"
        color: "0.89 0.91 0.93 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_Base_Assy.STL

  feeder_x_axis_mobile_base:
    visual:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_mobile.STL
      material:
        name: "Grey_feeder_x_axis_mobile_base"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_mobile.STL

  feeder_y_axis_plate:
    visual:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_y_plate.STL
      material:
        name: "Grey_feeder_y_axis_plate"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_y_plate.STL

  feeder_arm_base:
    visual:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_arm_base.STL
      material:
        name: "Grey_feeder_arm_base"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_arm_base.STL
  
  feeder_arm_slider:
    visual:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_arm_slider.STL
      material:
        name: "Grey_feeder_arm_slider"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_arm_slider.STL
  
  feeder_arm_plate:
    visual:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_arm_plate.STL
      material:
        name: "Grey_feeder_arm_plate"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/feeder/Supply_Device_RnD_arm_plate.STL

