shoulder_pan_joint: -3.72
shoulder_lift_joint: -1.155004847
elbow_joint: -1.623660393
wrist_1_joint: -1.559093451
wrist_2_joint: 1.740479197
wrist_3_joint: -0.009424778
tooltip1_joint: 0.0
tooltip2_joint: 0.0
arf_axis_1_joint: 0.0
arf_axis_2_joint: 0.0
denso_joint_1: 0.0
denso_joint_2: 0.0
denso_joint_3: 0.296
denso_joint_4: 0.0 
denso_axis_joint: 0.0
arf_gripper_joint_1: -0.0744
arf_gripper_joint_2: 0.0744
supply_y_axis_plate_joint: 0.0
supply_x_axis_mobile_base_joint: 0.0