# Visualisation

mesh_files:
  supply_base:
    visual:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_Base_Assy.STL
      material:
        name: "LightGrey_supply_base"
        color: "0.89 0.91 0.93 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_Base_Assy.STL

  supply_x_axis_mobile_base:
    visual:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_mobile.STL
      material:
        name: "Grey_supply_x_axis_mobile_base"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_mobile.STL

  supply_y_axis_plate:
    visual:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_y_plate.STL
      material:
        name: "Grey_supply_y_axis_plate"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_y_plate.STL

  supply_arm_base:
    visual:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_arm_base.STL
      material:
        name: "Grey_supply_arm_base"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_arm_base.STL
  
  supply_arm_slider:
    visual:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_arm_slider.STL
      material:
        name: "Grey_supply_arm_slider"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_arm_slider.STL
  
  supply_arm_plate:
    visual:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_arm_plate.STL
      material:
        name: "Grey_supply_arm_plate"
        color: "0.4 0.42 0.45 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/supply/Supply_Device_RnD_arm_plate.STL

