# These limits are used by MoveIt and augment/override the definitions in ur_description.
#
# While the robot does not inherently have any limits on joint accelerations (only on torques),
# MoveIt needs them for time parametrization. They were chosen conservatively to work in most use
# cases. For specific applications, higher values might lead to better execution performance.

joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0

# Denso robot joint limits
denso_joint_limits:
  denso_joint_1:
    has_acceleration_limits: true
    max_acceleration: 5.0
  denso_joint_2:
    has_acceleration_limits: true
    max_acceleration: 5.0
  denso_joint_3:
    has_acceleration_limits: true
    max_acceleration: 5.0
  denso_joint_4:
    has_acceleration_limits: true
    max_acceleration: 5.0
