/**:
  ros__parameters:
    robot_description_kinematics:
      ur_manipulator:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.001
        kinematics_solver_timeout: 0.3
        kinematics_solver_attempts: 25
      denso_arm:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.001
        kinematics_solver_timeout: 0.3
        kinematics_solver_attempts: 25
